# -*- coding: utf-8 -*-
{
    'name': 'NN Fund Management',
    'version': '17.0.1.0.0',
    'summary': 'Manage incoming funds, allocations, requisitions, bills, and transfers with multi-level approval workflow.',
    'category': 'Finance',
    'author': 'Imtiaz Ahmed',
    'website': 'https://github.com/ImtiazAhmed01/NN_Fund_Management',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/sequence.xml',
        'views/menus.xml',
        'views/fund_account_views.xml',
        'views/incoming_fund_views.xml',
        'views/project_views.xml',
        'views/expense_head_views.xml',
        'views/allocation_views.xml',
        'views/requisition_views.xml',
        'views/transfer_views.xml',
        'views/bill_views.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
